name: 'git Subtree Split'
description: 'use the git subtree split command as part of your build process'
inputs:
  prefix:  # name of the package
    description: 'Name of the folder to perform the subtree split on'
    required: true
  branch:
    description: 'name of the branch to be created/updated for the subtree split'
    required: true
  tag:
    description: 'Version postfix'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "gray-dark"
  icon: "box" 
