name: 'Unity Package Publish'
description: 'Publish unity package using package.json'
inputs:
  name:  # name of the package
    description: 'Package name i.e. com.mycompany.mypackage'
    required: true
  upmBranch:
    description: 'UPM branch to publish the package'
    required: true
    default: 'upm'
  versionPostfix:
    description: 'Version postfix'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: "gray-dark"
  icon: "box" 
